export type ApparelItem = {
  name: string;
  img: string;
  desc: string;
  color: string;
  description: string;
  categories: string[];
  price: number;
  material: string;
  sequence: number;
  remarks: string;
  updatedAt: string;
  createdAt: string;
  isActive: boolean;
  isDeleted: boolean;
};

export const apparelItems: ApparelItem[] = [
  {
    name: "Blue Waves Mini Dress",
    img: "https://via.placeholder.com/150",
    desc: "Timeless denim jacket with a modern twist.",
    color: "Blue",
    description:
      "A must-have staple for any wardrobe, this classic denim jacket features durable stitching, silver-tone buttons, and a structured fit perfect for layering.",
    categories: ["Jackets", "Denim"],
    price: 59.99,
    material: "100% Cotton",
    sequence: 1,
    remarks: "Available in sizes XS to XL",
    updatedAt: "2025-05-20T08:10:00Z",
    createdAt: "2025-03-15T14:32:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Tanjun Pants",
    img: "https://via.placeholder.com/150",
    desc: "Versatile slim chinos for casual or formal looks.",
    color: "Khaki",
    description:
      "Crafted with a stretchable cotton blend, these slim-fit chinos deliver comfort and style, ideal for both office wear and weekend outings.",
    categories: ["Pants", "Casual"],
    price: 44.95,
    material: "Cotton-Spandex Blend",
    sequence: 2,
    remarks: "Machine washable",
    updatedAt: "2025-05-18T11:00:00Z",
    createdAt: "2025-02-21T12:00:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Cotton Graphic Tee",
    img: "https://via.placeholder.com/150",
    desc: "Comfortable tee with bold graphic print.",
    color: "White",
    description:
      "Soft cotton t-shirt featuring a bold front graphic and relaxed fit. Perfect for everyday casual style.",
    categories: ["T-Shirts", "Casual"],
    price: 24.5,
    material: "100% Cotton",
    sequence: 3,
    remarks: "Limited edition print",
    updatedAt: "2025-05-22T14:23:00Z",
    createdAt: "2025-03-01T10:00:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Wool Blend Overcoat",
    img: "https://via.placeholder.com/150",
    desc: "Elegant long overcoat for cold weather.",
    color: "Charcoal",
    description:
      "This overcoat is tailored from a rich wool blend for warmth and sophistication. Features a structured silhouette with front pockets and button closure.",
    categories: ["Outerwear", "Formal"],
    price: 149.99,
    material: "Wool-Polyester Blend",
    sequence: 4,
    remarks: "Dry clean only",
    updatedAt: "2025-05-24T09:30:00Z",
    createdAt: "2025-01-10T08:20:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "High-Waisted Jeans",
    img: "https://via.placeholder.com/150",
    desc: "Flattering high-rise jeans with a slim fit.",
    color: "Dark Blue",
    description:
      "Designed to sculpt and shape, these high-waisted jeans offer both comfort and style with a touch of stretch and a tapered leg.",
    categories: ["Jeans", "Women"],
    price: 64.99,
    material: "Cotton, Elastane",
    sequence: 5,
    remarks: "Stretchable fit",
    updatedAt: "2025-05-19T13:45:00Z",
    createdAt: "2025-03-22T07:50:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Boho Maxi Dress",
    img: "https://via.placeholder.com/150",
    desc: "Flowy maxi dress with floral prints.",
    color: "Multicolor",
    description:
      "This breezy bohemian-style maxi dress features floral patterns, a cinched waist, and lightweight fabric perfect for summer days.",
    categories: ["Dresses", "Bohemian"],
    price: 74.95,
    material: "Rayon",
    sequence: 6,
    remarks: "Pairs well with sandals",
    updatedAt: "2025-05-25T09:00:00Z",
    createdAt: "2025-04-02T15:00:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Athleisure Hoodie",
    img: "https://via.placeholder.com/150",
    desc: "Cozy hoodie for workouts and chillouts.",
    color: "Heather Gray",
    description:
      "Stay warm and stylish with this soft fleece hoodie, perfect for workouts or lounging at home. Features a kangaroo pocket and adjustable drawstring hood.",
    categories: ["Hoodies", "Activewear"],
    price: 39.95,
    material: "Polyester-Cotton Blend",
    sequence: 7,
    remarks: "Unisex fit",
    updatedAt: "2025-05-20T16:00:00Z",
    createdAt: "2025-03-18T13:12:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Linen Short Sleeve Shirt",
    img: "https://via.placeholder.com/150",
    desc: "Breathable linen shirt for hot weather.",
    color: "Beige",
    description:
      "Lightweight and breathable, this linen shirt is a warm-weather essential with a relaxed cut and button-down collar.",
    categories: ["Shirts", "Summer"],
    price: 34.99,
    material: "100% Linen",
    sequence: 8,
    remarks: "Wrinkle-prone",
    updatedAt: "2025-05-23T10:45:00Z",
    createdAt: "2025-04-01T08:00:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Faux Leather Skirt",
    img: "https://via.placeholder.com/150",
    desc: "Chic faux leather skirt with side zip.",
    color: "Black",
    description:
      "Make a statement with this edgy faux leather mini skirt. Features a side zipper and flattering high waist fit.",
    categories: ["Skirts", "Partywear"],
    price: 49.99,
    material: "PU Leather",
    sequence: 9,
    remarks: "Vegan-friendly",
    updatedAt: "2025-05-21T12:00:00Z",
    createdAt: "2025-03-05T11:00:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Basic Crewneck Tee",
    img: "https://via.placeholder.com/150",
    desc: "Everyday essential tee with soft feel.",
    color: "Olive",
    description:
      "An everyday essential crafted from soft cotton with a relaxed fit. Ideal for layering or wearing solo.",
    categories: ["T-Shirts", "Essentials"],
    price: 19.99,
    material: "100% Organic Cotton",
    sequence: 10,
    remarks: "Sustainable material",
    updatedAt: "2025-05-22T17:00:00Z",
    createdAt: "2025-02-28T09:00:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Striped Button-Up Shirt",
    img: "https://via.placeholder.com/150",
    desc: "Smart-casual shirt with vertical stripes.",
    color: "White/Blue",
    description:
      "A modern twist on a classic design, this striped button-up shirt is great for business-casual settings or weekend brunches.",
    categories: ["Shirts", "Smart Casual"],
    price: 42.5,
    material: "Cotton-Polyester Blend",
    sequence: 11,
    remarks: "Slim fit available",
    updatedAt: "2025-05-23T12:30:00Z",
    createdAt: "2025-03-12T11:20:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Ribbed Knit Sweater",
    img: "https://via.placeholder.com/150",
    desc: "Cozy ribbed sweater with stretch fit.",
    color: "Cream",
    description:
      "This soft rib-knit sweater hugs your body while providing warmth and comfort. Ideal for layering or standalone style.",
    categories: ["Sweaters", "Winterwear"],
    price: 54.99,
    material: "Viscose Blend",
    sequence: 12,
    remarks: "Stretch fabric",
    updatedAt: "2025-05-24T09:40:00Z",
    createdAt: "2025-01-30T10:00:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Oversized Hoodie",
    img: "https://via.placeholder.com/150",
    desc: "Relaxed-fit hoodie for extra comfort.",
    color: "Moss Green",
    description:
      "Made for cozy days, this oversized hoodie features soft fleece lining, dropped shoulders, and a slouchy fit.",
    categories: ["Hoodies", "Loungewear"],
    price: 44.0,
    material: "Cotton Fleece",
    sequence: 13,
    remarks: "Unisex design",
    updatedAt: "2025-05-25T08:00:00Z",
    createdAt: "2025-04-10T13:30:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Tailored Blazer",
    img: "https://via.placeholder.com/150",
    desc: "Structured blazer with peak lapel.",
    color: "Navy",
    description:
      "Add polish to any outfit with this structured blazer. Cut to flatter and built with shoulder padding for sharp lines.",
    categories: ["Blazers", "Formal"],
    price: 89.0,
    material: "Polyester-Viscose",
    sequence: 14,
    remarks: "True to size",
    updatedAt: "2025-05-22T10:15:00Z",
    createdAt: "2025-02-25T09:00:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Flared Yoga Pants",
    img: "https://via.placeholder.com/150",
    desc: "Flexible yoga pants with flare bottom.",
    color: "Charcoal",
    description:
      "These high-waisted yoga pants offer a supportive waistband and flared hem for a trendy, flattering look during workouts or errands.",
    categories: ["Activewear", "Pants"],
    price: 39.95,
    material: "Nylon-Spandex",
    sequence: 15,
    remarks: "Sweat-wicking fabric",
    updatedAt: "2025-05-19T15:00:00Z",
    createdAt: "2025-03-28T14:00:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Cable Knit Cardigan",
    img: "https://via.placeholder.com/150",
    desc: "Warm cardigan with textured cable knit.",
    color: "Taupe",
    description:
      "Stay warm with this chunky cable knit cardigan featuring front buttons and front patch pockets. A cozy layering essential.",
    categories: ["Cardigans", "Knitwear"],
    price: 59.99,
    material: "Acrylic Wool Blend",
    sequence: 16,
    remarks: "Hand wash only",
    updatedAt: "2025-05-21T14:00:00Z",
    createdAt: "2025-03-07T10:30:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Pleated Midi Skirt",
    img: "https://via.placeholder.com/150",
    desc: "Elegant pleated skirt with flowy shape.",
    color: "Dusty Rose",
    description:
      "A feminine and elegant pleated midi skirt that moves beautifully with every step. Features an elastic waistband and lightweight fabric.",
    categories: ["Skirts", "Feminine"],
    price: 47.5,
    material: "Polyester",
    sequence: 17,
    remarks: "No ironing needed",
    updatedAt: "2025-05-23T18:00:00Z",
    createdAt: "2025-03-13T09:00:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Printed Crop Top",
    img: "https://via.placeholder.com/150",
    desc: "Trendy crop top with floral print.",
    color: "Lilac",
    description:
      "Fun and flirty, this floral printed crop top pairs great with high-waisted jeans or skirts. Features a smocked back for added comfort.",
    categories: ["Tops", "Trendy"],
    price: 28.0,
    material: "Cotton Blend",
    sequence: 18,
    remarks: "Fits true to size",
    updatedAt: "2025-05-24T11:00:00Z",
    createdAt: "2025-04-04T12:00:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Puffer Vest",
    img: "https://via.placeholder.com/150",
    desc: "Quilted vest for chilly mornings.",
    color: "Olive Green",
    description:
      "Lightweight and insulated, this puffer vest is perfect for layering in transitional weather. Features zip front and side pockets.",
    categories: ["Outerwear", "Vests"],
    price: 65.0,
    material: "Nylon Fill",
    sequence: 19,
    remarks: "Water-resistant",
    updatedAt: "2025-05-25T07:50:00Z",
    createdAt: "2025-04-08T15:30:00Z",
    isActive: true,
    isDeleted: false,
  },
  {
    name: "Sleeveless Bodycon Dress",
    img: "https://via.placeholder.com/150",
    desc: "Curve-hugging dress for evenings out.",
    color: "Black",
    description:
      "Turn heads with this sleek sleeveless bodycon dress. Designed to contour the body with a smooth finish, perfect for night-outs and formal dinners.",
    categories: ["Dresses", "Eveningwear"],
    price: 79.99,
    material: "Polyester-Spandex",
    sequence: 20,
    remarks: "Zipper closure at back",
    updatedAt: "2025-05-25T12:00:00Z",
    createdAt: "2025-04-18T16:00:00Z",
    isActive: true,
    isDeleted: false,
  },
  // 10 more items can be generated similarly upon request
];
